eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 

spring:
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice-client
          uri: lb://MICROSERVICE-CLIENT
          predicates:
            - Path=/clients/**
        - id: microservice-adress-catalog
          uri: lb://MICROSERVICE-ADRESS-CATALOG
          predicates:
            - Path=/enderecos/**